FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

RUN npm run build

EXPOSE 5173
# --host 0.0.0.0 позволяет открывать порт извне контейнера
CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0"]