name: build-and-lint

# triggers: define when this workflow should run
# trigger on push to these branches
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

    # define a job (multiple jobs also)
jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: |
            server/package-lock.json
            client/package-lock.json

      - name: Install backend dependencies
        working-directory: server
        run: |
          npm ci
          npm run lint -- --max-warnings=0

      - name: Lint backend
        working-directory: server
        run: npm run lint -- --max-warnings=0

      - name: Install frontend dependencies
        working-directory: client
        run: |
          npm ci
          npm run lint -- --max-warnings=0

      - name: Lint frontend
        working-directory: client
        run: npm run lint -- --max-warnings=0

      - name: Build backend image
        run: docker build -t backend ./server

      - name: Build frontend image
        run: docker build -t frontend ./client

  deploy:
    needs: build-and-lint
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: Add EC2 host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}

      - name: Write SSH key
        run: |
          echo "${EC2_KEY}" > ec2_key.pem
          chmod 600 ec2_key.pem
        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}

      - name: Deploy on EC2 (git pull + docker compose up -d --build)
        run: |
          # 1. Формируем файл скрипта локально
          cat << 'EOF' > deploy.sh
          set -e
          echo "1. Успешное подключение к серверу!"

          mkdir -p ~/${{ secrets.EC2_APP_DIR }}
          cd ~/${{ secrets.EC2_APP_DIR }}

          if [ ! -d ".git" ]; then
            echo "2. Инициализация гит-репозитория..."
            git init
            git remote add origin https://github.com/timaZhuk/DevOps-NERN-practice.git
          fi

          echo "3. Обновление кода..."
          git fetch --all
          git reset --hard origin/main

          echo "4. Создание .env файлов..."
          cat << 'ENV_EOF' > .env
          MONGO_URI=${{ secrets.MONGO_URI }}
          PORT=${{ secrets.PORT }}
          VITE_API_URL=${{ secrets.VITE_API_URL }}
          ENV_EOF

          mkdir -p server client
          cp .env ./server/.env
          cp .env ./client/.env

          echo "5. Запуск Docker..."
          docker compose up -d --build
          docker image prune -f
          docker compose ps
          EOF

          # 2. Передаем скрипт на сервер Ubuntu 24.04 (в папку /tmp/ ok)
          scp -i ec2_key.pem -o StrictHostKeyChecking=no deploy.sh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/deploy.sh

          # 3. Выполняем переданный скрипт
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "bash /tmp/deploy.sh"
